name: Release MV2

on:
  push:
    branches: [ mv2 ]

jobs:
  release:
    if: contains(github.event.head_commit.message, '[publish]')
    runs-on: ubuntu-latest
    steps:
      - name: Package extension
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r extension.zip src icons manifest.json

      - uses: canastro/copy-file-action@master
        with:
          source: "extension.zip"
          target: "extension.xpi"

      - name: Push to Firefox Addon store
        uses: trmcnvn/firefox-addon@v1
        with:
          uuid: cumchrome@cumcord.com
          xpi: extension.xpi
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}

      - name: Release to GitHub
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          prerelease: false
          automatic_release_tag: mv2
          files: |
            extension.zip
            extension.xpi